#SPDX-License-Identifier: MIT-0
---
# tasks file for lab_postgresql
- name: create docker compose postgresql dir
  file:
    path: /opt/docker/postgresql
    state: directory
    group: dev
    mode: "0770"

- name: generate ssh keys
  openssh_keypair:
    path: /home/ubuntu/.ssh/vps_tunnel_key
    type: ed25519
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  register: tunnel_key

- name: generated public key copy to vps
  authorized_key:
    user: "{{ vps_user }}"
    state: present
    key: "{{ tunnel_key.public_key }}"
  delegate_to: vps_msk 

- name: copy docker compose file
  template:
    src: compose.yml.j2
    dest: /opt/docker/postgresql/compose.yml
    group: dev
    mode: "0770"

- name: start docker compose
  community.docker.docker_compose_v2:
    project_src: /opt/docker/postgresql
    state: present

#временно сюды ..:D
