#SPDX-License-Identifier: MIT-0
---
# tasks file for vps_ssh_tunnel
- name: configure sshd gateway ports for tunnel
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(#\s*)?GatewayPorts\b'
    line: 'GatewayPorts yes'
    backup: yes
  notify: restart ssh

- name: Add tunnel public key to VPS
  authorized_key:
    user: admin          
    state: present
    key: "{{ lookup('file', '~/.ssh/vps_tunnel_key.pub') }}" 