---
- name: deploy HomeLab infrastructure
  hosts: all_homelab_servers
  roles:
    - lab_netbird   
    - lab_postgresql  
    - lab_ssh_tunnel  

- name: deploy nginx to vps
  hosts: vps_msk
  roles:
    - vps_nginx       

- name: deploy vps applications & gateways
  hosts: vps_msk
  roles:
    - vps_nginx_html  
    - vps_ssh_tunnel  