---
- hosts: docker_psql
  hosts: lab_db
  roles:
#    - lab_docker_install
#    - lab_postgresql
    - lab_netbird

- name: vscode
  hosts: lab_vscode_srv
  roles:
    - lab_docker_install
    - lab_netbird
    - lab_vscode