#SPDX-License-Identifier: MIT-0
---
# tasks file for lab_netbird
- name: create folder for netbird
  file:
    path: /opt/docker/netbird
    state: directory
    group: dev
    mode: "0770"

- name: copy docker compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/netbird/docker-compose.yml
    group: dev

- name: start docker compose
  community.docker.docker_compose_v2:
    project_src: /opt/docker/netbird
    state: present